services:
    app:
        image: ghcr.io/e-learning-by-sse/dev-env-javascript:latest
        entrypoint:
            - sleep
            - infinity
        init: true
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
            - ./:/code
